# GoReleaser Configuration for SQLBlade
# This is a Go library, so we mainly need to create GitHub releases

project_name: sqlblade

# Since this is a library, we don't need to build binaries
builds:
  - skip: true  # Skip binary builds for library

# Skip Docker, Snapshot, Homebrew, Scoop since this is a library
dockers:
  skip: true

snapcrafts:
  skip: true

brews:
  skip: true

scoops:
  skip: true

# GitHub release
release:
  github:
    owner: alicanli1995
    name: sqlblade
  mode: replace
  footer: |
    ## Installation

    ```bash
    go get github.com/alicanli1995/sqlblade@{{ .Tag }}
    ```

    Full documentation: https://github.com/alicanli1995/sqlblade

# Changelog
changelog:
  skip: false
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

# For libraries, we mainly need the release and changelog
# No need for archives or checksums for a library
archives:
  skip: true

checksum:
  skip: true

# Publish to pkg.go.dev is automatic when tag is pushed

